services:
  integration:
    build:
      context: ..
      dockerfile: build/integration/Dockerfile
    container_name: integration
    restart: on-failure
    env_file:
      - integration.env

  storage:
    image: postgres
    container_name: storage
    restart: always
    env_file:
      - storage.env
    ports:
      - "5432:5432"
    volumes:
      - storage_volume:/var/lib/postgresql/data

  engine:
    build:
      context: ..
      dockerfile: build/engine/Dockerfile
    container_name: engine
    restart: always
    env_file:
      - engine.env
    depends_on:
      - integration
      - storage

  gateway:
    build:
      context: ..
      dockerfile: build/gateway/Dockerfile
    container_name: gateway
    restart: always
    env_file:
      - gateway.env
    ports:
      - "8080:8080"
    depends_on:
      - engine

  report:
    build:
      context: ..
      dockerfile: build/report/Dockerfile
    container_name: report
    restart: always
    env_file:
      - report.env
    ports:
      - "8081:8081"
    depends_on:
      - engine

volumes:
  storage_volume:
