// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.6
// source: api/proto/integration/integration.proto

package integration

import (
	shared "github.com/tmrrwnxtsn/ecomway/api/proto/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailableMethodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionType shared.TransactionType `protobuf:"varint,1,opt,name=transaction_type,json=transactionType,proto3,enum=shared.TransactionType" json:"transaction_type,omitempty"`
	Currency        string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	ExternalSystem  *string                `protobuf:"bytes,3,opt,name=external_system,json=externalSystem,proto3,oneof" json:"external_system,omitempty"`
}

func (x *AvailableMethodsRequest) Reset() {
	*x = AvailableMethodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_integration_integration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMethodsRequest) ProtoMessage() {}

func (x *AvailableMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integration_integration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMethodsRequest.ProtoReflect.Descriptor instead.
func (*AvailableMethodsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_integration_integration_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableMethodsRequest) GetTransactionType() shared.TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return shared.TransactionType(0)
}

func (x *AvailableMethodsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AvailableMethodsRequest) GetExternalSystem() string {
	if x != nil && x.ExternalSystem != nil {
		return *x.ExternalSystem
	}
	return ""
}

type AvailableMethodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Methods []*shared.Method `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *AvailableMethodsResponse) Reset() {
	*x = AvailableMethodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_integration_integration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMethodsResponse) ProtoMessage() {}

func (x *AvailableMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integration_integration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMethodsResponse.ProtoReflect.Descriptor instead.
func (*AvailableMethodsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_integration_integration_proto_rawDescGZIP(), []int{1}
}

func (x *AvailableMethodsResponse) GetMethods() []*shared.Method {
	if x != nil {
		return x.Methods
	}
	return nil
}

var File_api_proto_integration_integration_proto protoreflect.FileDescriptor

var file_api_proto_integration_integration_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x17, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x42, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x2c, 0x0a, 0x0f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x88, 0x01, 0x01, 0x42,
	0x12, 0x0a, 0x10, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x22, 0x44, 0x0a, 0x18, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x32, 0x75, 0x0a, 0x12, 0x49, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5f, 0x0a, 0x10, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x12, 0x24, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x6d, 0x72, 0x72, 0x77, 0x6e, 0x78, 0x74, 0x73, 0x6e, 0x2f, 0x65, 0x63, 0x6f, 0x6d, 0x77, 0x61,
	0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_integration_integration_proto_rawDescOnce sync.Once
	file_api_proto_integration_integration_proto_rawDescData = file_api_proto_integration_integration_proto_rawDesc
)

func file_api_proto_integration_integration_proto_rawDescGZIP() []byte {
	file_api_proto_integration_integration_proto_rawDescOnce.Do(func() {
		file_api_proto_integration_integration_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_integration_integration_proto_rawDescData)
	})
	return file_api_proto_integration_integration_proto_rawDescData
}

var file_api_proto_integration_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_integration_integration_proto_goTypes = []interface{}{
	(*AvailableMethodsRequest)(nil),  // 0: integration.AvailableMethodsRequest
	(*AvailableMethodsResponse)(nil), // 1: integration.AvailableMethodsResponse
	(shared.TransactionType)(0),      // 2: shared.TransactionType
	(*shared.Method)(nil),            // 3: shared.Method
}
var file_api_proto_integration_integration_proto_depIdxs = []int32{
	2, // 0: integration.AvailableMethodsRequest.transaction_type:type_name -> shared.TransactionType
	3, // 1: integration.AvailableMethodsResponse.methods:type_name -> shared.Method
	0, // 2: integration.IntegrationService.AvailableMethods:input_type -> integration.AvailableMethodsRequest
	1, // 3: integration.IntegrationService.AvailableMethods:output_type -> integration.AvailableMethodsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_integration_integration_proto_init() }
func file_api_proto_integration_integration_proto_init() {
	if File_api_proto_integration_integration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_integration_integration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableMethodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_integration_integration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableMethodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_integration_integration_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_integration_integration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_integration_integration_proto_goTypes,
		DependencyIndexes: file_api_proto_integration_integration_proto_depIdxs,
		MessageInfos:      file_api_proto_integration_integration_proto_msgTypes,
	}.Build()
	File_api_proto_integration_integration_proto = out.File
	file_api_proto_integration_integration_proto_rawDesc = nil
	file_api_proto_integration_integration_proto_goTypes = nil
	file_api_proto_integration_integration_proto_depIdxs = nil
}
