// Package v1 Code generated by swaggo/swag. DO NOT EDIT
package v1

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Курмыза Павел",
            "email": "tmrrwnxtsn@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/operation": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Операции"
                ],
                "summary": "Получить список операций по заданным фильтрам",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор специалиста техподдержки",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Код языка, обозначение по RFC 5646",
                        "name": "lang_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Идентификатор операции",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Идентификатор операции на стороне платежной системы",
                        "name": "external_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Идентификатор клиента",
                        "name": "client_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип операции",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Внутренние статусы операций, перечисленные через запятую",
                        "name": "statuses",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Время создания операции в формате UNIX Timestamp, с которого возвращать результирующие операции",
                        "name": "created_at_from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Время создания операции в формате UNIX Timestamp, до которого возвращать результирующие операции",
                        "name": "created_at_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле для сортировки результирующего списка (по умолчанию - id)",
                        "name": "order_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип сортировки (по умолчанию - DESC, по убыванию)",
                        "name": "order_type",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Флаг о необходимости вернуть результат в формате CSV (по умолчанию - false)",
                        "name": "csv",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "$ref": "#/definitions/v1.operationListResponse"
                        }
                    },
                    "default": {
                        "description": "Ответ с ошибкой",
                        "schema": {
                            "$ref": "#/definitions/v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/operation/{id}/external-status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Операции"
                ],
                "summary": "Запросить статус операции на стороне платежной системы",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор операции",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Идентификатор специалиста техподдержки",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Код языка, обозначение по RFC 5646",
                        "name": "lang_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "$ref": "#/definitions/v1.operationExternalStatusResponse"
                        }
                    },
                    "default": {
                        "description": "Ответ с ошибкой",
                        "schema": {
                            "$ref": "#/definitions/v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/tool": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Платежные средства"
                ],
                "summary": "Получить список платежных средств клиента",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор специалиста техподдержки",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Код языка, обозначение по RFC 5646",
                        "name": "lang_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Идентификатор клиента",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "$ref": "#/definitions/v1.toolListResponse"
                        }
                    },
                    "default": {
                        "description": "Ответ с ошибкой",
                        "schema": {
                            "$ref": "#/definitions/v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/tool/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Платежные средства"
                ],
                "summary": "Удалить платежное средство",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.toolRemoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "$ref": "#/definitions/v1.toolRemoveResponse"
                        }
                    },
                    "default": {
                        "description": "Ответ с ошибкой",
                        "schema": {
                            "$ref": "#/definitions/v1.errorResponse"
                        }
                    }
                }
            }
        },
        "/tool/recover": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Платежные средства"
                ],
                "summary": "Установить платежное средство готовым к восстановлению",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.toolRecoverRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "$ref": "#/definitions/v1.toolRecoverResponse"
                        }
                    },
                    "default": {
                        "description": "Ответ с ошибкой",
                        "schema": {
                            "$ref": "#/definitions/v1.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.errorContent": {
            "type": "object",
            "required": [
                "code",
                "description"
            ],
            "properties": {
                "code": {
                    "description": "Код ошибки",
                    "type": "string",
                    "example": "InvalidRequest"
                },
                "description": {
                    "description": "Описание ошибки для разработки",
                    "type": "string",
                    "example": "user_id param is required"
                },
                "message": {
                    "description": "Сообщение об ошибке для клиента",
                    "type": "string",
                    "example": "Internal server error occurred. Please try again later."
                }
            }
        },
        "v1.errorResponse": {
            "type": "object",
            "required": [
                "error",
                "success"
            ],
            "properties": {
                "error": {
                    "description": "Развернутая информация об ошибке",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.errorContent"
                        }
                    ]
                },
                "success": {
                    "description": "Результат обработки запроса (всегда false)",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "v1.operation": {
            "type": "object",
            "required": [
                "amount",
                "client_id",
                "created_at",
                "currency",
                "id",
                "status",
                "type",
                "updated_at"
            ],
            "properties": {
                "amount": {
                    "description": "Сумма операции",
                    "type": "number",
                    "example": 121.01
                },
                "client_id": {
                    "description": "Идентификатор клиента",
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "description": "Время создания операции в формате UNIX Timestamp",
                    "type": "integer",
                    "example": 1715974447
                },
                "currency": {
                    "description": "Валюта операции",
                    "type": "string",
                    "example": "RUB"
                },
                "external_id": {
                    "description": "Идентификатор операции на стороне платежной системы",
                    "type": "string",
                    "example": "ew01r01w0gfw1fw1"
                },
                "external_status": {
                    "description": "Статус операции на стороне платежной системы",
                    "type": "string",
                    "example": "PENDING"
                },
                "fail_reason": {
                    "description": "Причина отклонения операции",
                    "type": "string",
                    "example": "Technical error"
                },
                "id": {
                    "description": "Идентификатор операции",
                    "type": "integer",
                    "example": 1
                },
                "processed_at": {
                    "description": "Время завершения операции на стороне платежной системы в формате UNIX Timestamp",
                    "type": "integer",
                    "example": 1715974447
                },
                "status": {
                    "description": "Внутренний статус операции",
                    "type": "string",
                    "example": "SUCCESS"
                },
                "tool": {
                    "description": "Платежное средство, используемое в операции",
                    "type": "string",
                    "example": "5748********4124"
                },
                "type": {
                    "description": "Тип операции",
                    "type": "string",
                    "example": "payment"
                },
                "updated_at": {
                    "description": "Время последнего обновления операции в формате UNIX Timestamp",
                    "type": "integer",
                    "example": 1715974447
                }
            }
        },
        "v1.operationExternalStatusResponse": {
            "type": "object",
            "required": [
                "external_status",
                "message",
                "success"
            ],
            "properties": {
                "external_status": {
                    "description": "Статус операции на стороне платежной системы",
                    "type": "string",
                    "example": "PENDING"
                },
                "message": {
                    "description": "Информативное сообщение, описывающее статус транзакции на стороне платежной системы",
                    "type": "string",
                    "example": "Транзакция на стороне ПС еще не имеет конечный статус."
                },
                "success": {
                    "description": "Результат обработки запроса (всегда true)",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "v1.operationListResponse": {
            "type": "object",
            "required": [
                "operations",
                "success",
                "total_amount",
                "total_count"
            ],
            "properties": {
                "operations": {
                    "description": "Массив операций, подходящих под фильтры и условия запроса",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.operation"
                    }
                },
                "success": {
                    "description": "Результат обработки запроса (всегда true)",
                    "type": "boolean",
                    "example": true
                },
                "total_amount": {
                    "description": "Сумма всех операций из результирующего массива",
                    "type": "number",
                    "example": 1421.1
                },
                "total_count": {
                    "description": "Количество всех операций из результирующего массива",
                    "type": "integer",
                    "example": 15
                }
            }
        },
        "v1.tool": {
            "type": "object",
            "required": [
                "caption",
                "created_at",
                "external_method",
                "id",
                "name",
                "status",
                "type",
                "updated_at"
            ],
            "properties": {
                "caption": {
                    "description": "Значение платежного средства:\n* Маскированная банковская карта\n* Номер электронного кошелька",
                    "type": "string",
                    "example": "444444******4444"
                },
                "created_at": {
                    "description": "Время создания платежного средства в формате UNIX Timestamp",
                    "type": "integer",
                    "example": 1715974447
                },
                "details": {
                    "description": "Дополнительная информация о платежном средстве",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.toolDetails"
                        }
                    ]
                },
                "external_method": {
                    "description": "Внутренний код платежного метода платежной системы, к которой относится платежное средство",
                    "type": "string",
                    "example": "yookassa_bank_card"
                },
                "id": {
                    "description": "Идентификатор платежного средства",
                    "type": "string",
                    "example": "2dc32aa0-000f-5000-8000-16d7bc6cd09f"
                },
                "name": {
                    "description": "Название платежного средства",
                    "type": "string",
                    "example": "Карта брата"
                },
                "status": {
                    "description": "Статус платежного средства:\n* Доступен клиенту - \"ACTIVE\"\n* Удален клиентом - \"REMOVED_BY_CLIENT\"\n* Ожидает восстановления - \"PENDING_RECOVERY\"\n* Заблокирован техподдержкой - \"REMOVED_BY_ADMINISTRATOR\"",
                    "type": "string",
                    "example": "ACTIVE"
                },
                "type": {
                    "description": "Тип платежного средства:\n* Банковская карта - \"card\"\n* Электронный кошелек - \"wallet\"",
                    "type": "string",
                    "example": "card"
                },
                "updated_at": {
                    "description": "Время последнего обновления платежного средства в формате UNIX Timestamp",
                    "type": "integer",
                    "example": 1715974447
                }
            }
        },
        "v1.toolDetails": {
            "type": "object",
            "properties": {
                "bank_name": {
                    "description": "Название банка, выпустившего банковскую карту",
                    "type": "string",
                    "example": "Sberbank"
                },
                "card_holder": {
                    "description": "Владелец банковской карты",
                    "type": "string",
                    "example": "Ivanov Ivan"
                },
                "card_type": {
                    "description": "Тип банковской карты",
                    "type": "string",
                    "example": "Visa"
                },
                "expiry_month": {
                    "description": "Срок действия банковской карты (месяц, MM)",
                    "type": "integer",
                    "example": 10
                },
                "expiry_year": {
                    "description": "Срок действия банковской карты (год, YYYY)",
                    "type": "integer",
                    "example": 2023
                },
                "wallet_number": {
                    "description": "Номер электронного кошелька",
                    "type": "string",
                    "example": "410011758831136"
                }
            }
        },
        "v1.toolListResponse": {
            "type": "object",
            "required": [
                "success",
                "tools"
            ],
            "properties": {
                "success": {
                    "description": "Результат обработки запроса (всегда true)",
                    "type": "boolean",
                    "example": true
                },
                "tools": {
                    "description": "Массив платежных средств клиента",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.tool"
                    }
                }
            }
        },
        "v1.toolRecoverRequest": {
            "type": "object",
            "required": [
                "client_id",
                "external_method",
                "id",
                "lang_code",
                "user_id"
            ],
            "properties": {
                "client_id": {
                    "description": "Идентификатор клиента",
                    "type": "integer",
                    "example": 1
                },
                "external_method": {
                    "description": "Внутренний код платежного метода платежной системы, к которой относится платежное средство",
                    "type": "string",
                    "example": "yookassa_bank_card"
                },
                "id": {
                    "description": "Идентификатор платежного средства",
                    "type": "string",
                    "example": "2dc32aa0-000f-5000-8000-16d7bc6cd09f"
                },
                "lang_code": {
                    "description": "Код языка, обозначение по RFC 5646",
                    "type": "string",
                    "example": "en"
                },
                "user_id": {
                    "description": "Идентификатор специалиста поддержки",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.toolRecoverResponse": {
            "type": "object",
            "required": [
                "message",
                "success"
            ],
            "properties": {
                "message": {
                    "description": "Сообщение, которое необходимо показать специалисту техподдержки",
                    "type": "string",
                    "example": "Платежное средство удалено."
                },
                "success": {
                    "description": "Результат обработки запроса (всегда true)",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "v1.toolRemoveRequest": {
            "type": "object",
            "required": [
                "client_id",
                "external_method",
                "id",
                "lang_code",
                "user_id"
            ],
            "properties": {
                "client_id": {
                    "description": "Идентификатор клиента",
                    "type": "integer",
                    "example": 1
                },
                "external_method": {
                    "description": "Внутренний код платежного метода платежной системы, к которой относится платежное средство",
                    "type": "string",
                    "example": "yookassa_bank_card"
                },
                "id": {
                    "description": "Идентификатор платежного средства",
                    "type": "string",
                    "example": "2dc32aa0-000f-5000-8000-16d7bc6cd09f"
                },
                "lang_code": {
                    "description": "Код языка, обозначение по RFC 5646",
                    "type": "string",
                    "example": "en"
                },
                "user_id": {
                    "description": "Идентификатор специалиста поддержки",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.toolRemoveResponse": {
            "type": "object",
            "required": [
                "message",
                "success"
            ],
            "properties": {
                "message": {
                    "description": "Сообщение, которое необходимо показать специалисту техподдержки",
                    "type": "string",
                    "example": "Платежное средство удалено."
                },
                "success": {
                    "description": "Результат обработки запроса (всегда true)",
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Секретный ключ",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Шлюз финансовой отчетности E-commerce системы",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
