engine:
  grpc_address: ":9000"
  environment: "prod"

  wrong_confirmation_code_limit: 3

  scheduler:
    is_enabled: true
    tasks:
      finalize_operations:
        is_enabled: true
        interval: 5
        operation_batch_size: 100
        max_workers: 1
        actualize_status_intervals:
          10: 10
          15: 15
          25: 25
          40: 40
          65: 65
          105: 105
          180: 180
          285: 285
          465: 465
          750: 750
          1215: 1215
        external_system_lifetime:
          yookassa: 5

      request_payouts:
        is_enabled: true
        interval: 5
        operation_batch_size: 100
        max_workers: 1

services:
  integration:
    grpc_address: "integration:9001"
  smtp:
    host: "smtp.mail.ru"
    port: 465
    username: "towbooat@mail.ru"
