integration:
  grpc_address: ":9001"

  yookassa:
    api:
      base_url: "https://api.yookassa.ru/v3"
      shop_id: "365155"
      secret_key: "test_Y3Y-q38sNweIkPQawtC8mvJtecmBodEShgazQuvjs-Y"

    channels:
      yookassa_bank_card:
        code: "card"
        payment_method_type: "bank_card"

    methods:
      payment:
        - id: "CARD"
          name:
            ru: "Банковская карта"
            en: "Bank card"
          external_system: "yookassa"
          external_method: "yookassa_bank_card"
          limits:
            RUB:
              min_amount: 1.0
              max_amount: 350000.0
          commission:
            type: "percent"
            percent: 0.0

      payout:
        - id: "CARD"
          name:
            ru: "Банковская карта"
            en: "Bank card"
          external_system: "yookassa"
          external_method: "yookassa_bank_card"
          limits:
            RUB:
              min_amount: 100.0
              max_amount: 30000.0
          commission:
            type: "percent"
            percent: 0.0

services:
  engine:
    grpc_address: "engine:9000"
